name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login GHCR
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Build image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/dhia1911/flask-devops-project:latest .
          docker build -t ghcr.io/dhia1911/flask-devops-project:sha-${{ github.sha }} .

      # 4. Push image
      - name: Push Docker image
        run: |
          docker push ghcr.io/dhia1911/flask-devops-project:latest
          docker push ghcr.io/dhia1911/flask-devops-project:sha-${{ github.sha }}

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/dhia1911/flask-devops-project:latest
          format: table
          exit-code: "0"
          severity: HIGH,CRITICAL
      
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Deploy ${{ job.status }} 🚀\nRepo: ${{ github.repository }}\nTag: sha-${{ github.sha }}\nRun: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}